SET (CMAKE_SYSTEM_NAME Windows)
SET (CMAKE_SYSTEM_VERSION 10.0.17134)
SET (CMAKE_SYSTEM_PROCESSOR AMD64)
SET (TRIPLE x86_64-w64-windows-gnu)

SET (CMAKE_C_COMPILER               "clang")
SET (CMAKE_C_COMPILER_TARGET        ${TRIPLE})
SET (CMAKE_C_STANDARD               "11")
SET (CMAKE_C_STANDARD_REQUIRED      OFF)
SET (CMAKE_C_EXTENSIONS             OFF)
SET (CMAKE_C_FLAGS                  "-Wall -fuse-ld=lld -rtlib=compiler-rt")
SET (CMAKE_C_FLAGS_DEBUG            "-g -fcolor-diagnostics")
SET (CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG -flto")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g -DNDEBUG")
 
SET (CMAKE_CXX_COMPILER             "clang++")
SET (CMAKE_CXX_STANDARD             "17")
SET (CMAKE_CXX_STANDARD_REQUIRED    OFF)
SET (CMAKE_CXX_EXTENSIONS           OFF)
SET (CMAKE_CXX_FLAGS                "-Wall -fsjlj-exceptions -fuse-ld=lld")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g -fcolor-diagnostics")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -flto -rtlib=compiler-rt")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")

SET (CMAKE_LINKER                   "ld.lld")
SET (CMAKE_EXE_LINKER_FLAGS         "-pthread")
SET (CMAKE_EXE_LINKER_FLAGS_RELEASE "-flto -L D:/LLVM/lib -lunwind")
SET (CMAKE_AR                       "llvm-ar")
SET (CMAKE_C_COMPILER_AR            "llvm-ar")
SET (CMAKE_CXX_COMPILER_AR          "llvm-ar")
SET (CMAKE_NM                       "llvm-nm")
SET (CMAKE_OBJDUMP                  "llvm-objdump")
SET (CMAKE_OBJCOPY                  "llvm-objcopy")
SET (CMAKE_RANLIB                   "llvm-ranlib")
SET (CMAKE_C_COMPILER_RANLIB        "llvm-ranlib")
SET (CMAKE_CXX_COMPILER_RANLIB      "llvm-ranlib")
SET (CMAKE_READELF                  "llvm-readelf")
SET (CMAKE_ADDR2LINE                "llvm-addr2line")
SET (CMAKE_DLLTOOL                  "llvm-dlltool")
SET (CMAKE_RC_COMPILER              "llvm-rc")
SET (CMAKE_STRIP                    "llvm-strip")