SET (CMAKE_SYSTEM_NAME Windows)
SET (CMAKE_SYSTEM_VERSION 10.0.17134)
SET (CMAKE_SYSTEM_PROCESSOR AMD64)
SET (TRIPLE x86_64-w64-windows-gnu)

SET (CMAKE_C_COMPILER               "gcc")
SET (CMAKE_C_COMPILER_TARGET        ${TRIPLE})
SET (CMAKE_C_STANDARD               "11")
SET (CMAKE_C_STANDARD_REQUIRED      OFF)
SET (CMAKE_C_EXTENSIONS             OFF)
SET (CMAKE_C_FLAGS                  "-Wall -fuse-ld=bfd")
SET (CMAKE_C_FLAGS_DEBUG            "-g")
SET (CMAKE_C_FLAGS_MINSIZEREL       "-Os -DNDEBUG")
SET (CMAKE_C_FLAGS_RELEASE          "-O3 -DNDEBUG -flto")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO   "-O2 -g -DNDEBUG")
 
SET (CMAKE_CXX_COMPILER             "g++")
SET (CMAKE_CXX_STANDARD             "17")
SET (CMAKE_CXX_STANDARD_REQUIRED    OFF)
SET (CMAKE_CXX_EXTENSIONS           OFF)
SET (CMAKE_CXX_FLAGS                "-Wall -fuse-ld=bfd")
SET (CMAKE_CXX_FLAGS_DEBUG          "-g")
SET (CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG")
SET (CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -flto")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")

SET (CMAKE_LINKER                   "ld")
SET (CMAKE_EXE_LINKER_FLAGS         "-pthread")
SET (CMAKE_EXE_LINKER_FLAGS_RELEASE "-flto")
SET (CMAKE_AR                       "ar")
SET (CMAKE_C_AR                     "gcc-ar")
SET (CMAKE_CXX_AR                   "gcc-ar")
SET (CMAKE_NM                       "nm")
SET (CMAKE_OBJCOPY                  "objcopy")
SET (CMAKE_OBJDUMP                  "objdump")
SET (CMAKE_READELF                  "readelf")
SET (CMAKE_RANLIB                   "ranlib")
SET (CMAKE_C_RANLIB                 "gcc-ranlib")
SET (CMAKE_CXX_RANLIB               "gcc-ranlib")
SET (CMAKE_ADDR2LINE                "addr2line")
SET (CMAKE_DLLTOOL                  "dlltool")
SET (CMAKE_RC_COMPILER              "windres")
SET (CMAKE_STRIP                    "strip")